# Generated by Django 3.0.6 on 2020-05-07 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=70)),
                ('plan', models.CharField(choices=[('1', 'free'), ('2', 'normal'), ('4', 'premium')], default='1', max_length=2)),
                ('date_start_plan', models.DateField(blank=True, null=True)),
                ('time_pay', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cod', models.IntegerField()),
                ('card_name', models.CharField(max_length=50)),
                ('date_expiration', models.DateField()),
                ('bank', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Account')),
                ('pleasures_author', models.ManyToManyField(to='bookflix.Author')),
                ('pleasures_editorial', models.ManyToManyField(to='bookflix.Editorial')),
                ('pleasures_gender', models.ManyToManyField(to='bookflix.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('on_normal', models.BooleanField(default=False)),
                ('on_premium', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Author')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Editorial')),
                ('genders', models.ManyToManyField(to='bookflix.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('on_normal', models.BooleanField(default=False)),
                ('on_premium', models.BooleanField(default=False)),
                ('video', models.URLField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookflix.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookflix.CreditCards'),
        ),
    ]
